
# IF STATEMENT 

# A=26
# B=108
# if B>A:
#     print("B is greater than A")

# age=input("What's your age?")
# if int(age)>19:
#     print("you are an adult")
# else:
#     print("you are under age ")
  


# score=int(input("Enter Your Marks:-"))

# if score>= 90:
#     print("Grade-A")
# elif score>=80: 
#    print("Grade-B")
# elif score>=70: 
#    print("Grade-C")
# else : 
#    print("Grade-D")

# number=int(input("Enter any Number:-"))

# if number>0:
#     print("This is Positive Number")
#     if number%2 == 0:
#         print("This is even Number")
#     else:
#         print("This is Odd Number")
# else:
#     if number == 0:
#         print("This is zero")
#     else:
#         print("This is negatice NUmber")
       

age=16
status="Major" if age>=18 else "Minor"
print(status)



value=None
if value:
    print("value is true")
else:
    print("Value is false")






